title: "Juan Luis Romero Sosa"
author: "Juan Luis Romero Sosa"
description: "University of California, Los Angeles"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: false                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "About Me", sidebaricon: home}
  - {file: "Publications.md", title: "Publications", sidebaricon: address-card}
  - {file: "CV.pdf", title: "CV", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:juanluisromerososa@hotmail.com"}
  - {title: GoogleScholar, icon: google, url: "https://scholar.google.com/citations?user=y07ImpgAAAAJ&hl=en", target: "_blank"}
  - {title: Github, icon: github, url: "https://jlromero12.github.io"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/my-orcid?orcid=0000-0002-3944-3461", target: "_blank"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
