title: "Juan Luis Romero Sosa"
author: "Juan Luis Romero Sosa"
description: "Personal Website for Neuroscientist Juan Luis Romero Sosa"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: false                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: "Home", sidebaricon: home}
  - {file: "README.md", title: "Publications", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:juanluisromerososa@hotmail.com"}
  - {title: Github, icon: github, url: "https://jlromero12.github.io/JLRomeroSosa.github.io/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
